version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoauthapiv1
      - POSTGRES_USER=osaid
      - POSTGRES_PASSWORD=root
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_NAME=djanogauthapiv1
      - POSTGRES_USER=osaid
      - POSTGRES_PASSWORD=root
    depends_on:
      - db
